[workspace]

members = [
    "2020/day01",
    "2020/day02",
    "2020/day03",
    "2020/day04",
    "2020/day06",
    "2020/day07",
    "2022/day01",
    "2022/day02",
    "2022/day03",
    "2022/day04",
    "2022/day05",
    "2022/day06",
    "2022/day07",
    "utility",
]
